### ISSUE TITLE
[Bug]: Apps do not compile with flutter 3.29.0

### ISSUE THREAD

**Issue by fleoparra** [Baseflow/flutter-google-api-availability#51]
### Please check the following before submitting a new issue.

- [x] I have searched the [existing issues](https://github.com/baseflow/flutter-google-api-availability/issues).
- [x] I have carefully [read the documentation](https://github.com/Baseflow/flutter-google-api-availability/blob/main/google_api_availability/README.md) and verified I have added the required platform specific configuration.

### Steps to reproduce

Create a project and use google_api_availability: ^5.0.0 using flutter 3.29.0. 

It shows build error: 

> /Users/leonardo/.pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/src/main/java/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.java:11: error: cannot find symbol
> import io.flutter.plugin.common.PluginRegistry.Registrar;
>                                               ^
>   symbol:   class Registrar
>   location: interface PluginRegistry
> /Users/leonardo/.pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/src/main/java/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.java:12: error: cannot find symbol
> import io.flutter.plugin.common.PluginRegistry.ViewDestroyListener;
>                                               ^
>   symbol:   class ViewDestroyListener
>   location: interface PluginRegistry
> /Users/leonardo/.pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/src/main/java/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.java:13: error: cannot find symbol
> import io.flutter.view.FlutterNativeView;
>                       ^
>   symbol:   class FlutterNativeView
>   location: package io.flutter.view
> /Users/leonardo/.pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/src/main/java/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.java:58: error: cannot find symbol
>   public static void registerWith(Registrar registrar) {
>                                   ^
>   symbol:   class Registrar
>   location: class GoogleApiAvailabilityPlugin
> /Users/leonardo/.pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/src/main/java/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.java:63: error: cannot find symbol
>     registrar.addViewDestroyListener(new ViewDestroyListener() {
>                                          ^
>   symbol:   class ViewDestroyListener
>   location: class GoogleApiAvailabilityPlugin
> /Users/leonardo/.pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/src/main/java/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.java:65: error: cannot find symbol
>       public boolean onViewDestroy(FlutterNativeView view) {
>                                    ^
>   symbol: class FlutterNativeView
> /Users/leonardo/.pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/src/main/java/com/baseflow/googleapiavailability/GoogleApiAvailabilityPlugin.java:64: error: method does not override or implement a method from a supertype
>       @Override
>       ^
> 7 errors
> 3 warnings
> 
> FAILURE: Build failed with an exception.

### Expected results

Do not show an error

### Actual results

Show an error in flutter 3.29.0

### Code sample

only import and use google_api_availability in .yaml file

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

5.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.29.0, on macOS 15.3 24D60 darwin-arm64, locale en-CO)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.97.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone de Fabio. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

```

</details>

**Comment by MertSaygili** [comment]
Same

**Comment by postflow** [comment]
Same. Someone already did fork?

**Comment by postflow** [comment]
try add to you pubspec.yaml 
  ```
google_api_availability_android:
    git:
      url: https://github.com/postflow/flutter-google-api-availability.git
      ref: main
      path: google_api_availability_android
```

**Comment by fluttersiast** [comment]
@TimHoogstrate would be awesome to publish new version as PRs merged.

**Comment by TimHoogstrate** [comment]
I've just released the new version of the AFP (5.0.1) and the Android package (1.1.1). I'll close this issue for now. Feel free to reopen when needed.
